In [1]:
import pandas as pd
import numpy as np
print("Libraries Imported")

Libraries Imported

In [2]:
url = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'
df = pd.read_csv(url)
print(df.head(10))

   Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2         1       3                              Miss. Laina Heikkinen
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
4         0       3                            Mr. William Henry Allen
5         0       3                                    Mr. James Moran
6         0       1                             Mr. Timothy J McCarthy
7         0       3                      Master. Gosta Leonard Palsson
8         1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9         1       2                 Mrs. Nicholas (Adele Achem) Nasser

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0    male  22.0                        1                        0   7.2500
1  female  38.0                        1                        0  71.2833
2  female  26.0                        0                        0   7.9250
3  female  35.0                        1                        0  53.1000
4    male  35.0                        0                        0   8.0500
5    male  27.0                        0                        0   8.4583
6    male  54.0                        0                        0  51.8625
7    male   2.0                        3                        1  21.0750
8  female  27.0                        0                        2  11.1333
9  female  14.0                        1                        0  30.0708

In [3]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Survived                 887 non-null    int64
 1   Pclass                   887 non-null    int64
 2   Name                     887 non-null    str
 3   Sex                      887 non-null    str
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64
 6   Parents/Children Aboard  887 non-null    int64
 7   Fare                     887 non-null    float64
dtypes: float64(2), int64(4), str(2)
memory usage: 55.6 KB
None

In [4]:
print(df.describe())

         Survived      Pclass         Age  Siblings/Spouses Aboard  \
count  887.000000  887.000000  887.000000               887.000000
mean     0.385569    2.305524   29.471443                 0.525366
std      0.487004    0.836662   14.121908                 1.104669
min      0.000000    1.000000    0.420000                 0.000000
25%      0.000000    2.000000   20.250000                 0.000000
50%      0.000000    3.000000   28.000000                 0.000000
75%      1.000000    3.000000   38.000000                 1.000000
max      1.000000    3.000000   80.000000                 8.000000

       Parents/Children Aboard       Fare
count               887.000000  887.00000
mean                  0.383315   32.30542
std                   0.807466   49.78204
min                   0.000000    0.00000
25%                   0.000000    7.92500
50%                   0.000000   14.45420
75%                   0.000000   31.13750
max                   6.000000  512.32920

In [5]:
print(df['Age'].mean())

29.471443066516347

In [6]:
print(df['Fare'].max())

512.3292

In [7]:
print(df['Survived'].value_counts())

Survived
0    545
1    342
Name: count, dtype: int64

In [9]:
print(df.loc[0])

Survived                                        0
Pclass                                          3
Name                       Mr. Owen Harris Braund
Sex                                          male
Age                                          22.0
Siblings/Spouses Aboard                         1
Parents/Children Aboard                         0
Fare                                         7.25
Name: 0, dtype: object

In [10]:
print(df.columns)

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Siblings/Spouses Aboard',
       'Parents/Children Aboard', 'Fare'],
      dtype='str')

In [11]:
print(df.loc[2:6])

   Survived  Pclass                                         Name     Sex  \
2         1       3                        Miss. Laina Heikkinen  female
3         1       1  Mrs. Jacques Heath (Lily May Peel) Futrelle  female
4         0       3                      Mr. William Henry Allen    male
5         0       3                              Mr. James Moran    male
6         0       1                       Mr. Timothy J McCarthy    male

    Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
2  26.0                        0                        0   7.9250
3  35.0                        1                        0  53.1000
4  35.0                        0                        0   8.0500
5  27.0                        0                        0   8.4583
6  54.0                        0                        0  51.8625

In [14]:
print(df.loc[2,'Age'])

26.0

In [15]:
print(df.loc[0])

Survived                                        0
Pclass                                          3
Name                       Mr. Owen Harris Braund
Sex                                          male
Age                                          22.0
Siblings/Spouses Aboard                         1
Parents/Children Aboard                         0
Fare                                         7.25
Name: 0, dtype: object

In [16]:
print(df.iloc[0])

Survived                                        0
Pclass                                          3
Name                       Mr. Owen Harris Braund
Sex                                          male
Age                                          22.0
Siblings/Spouses Aboard                         1
Parents/Children Aboard                         0
Fare                                         7.25
Name: 0, dtype: object

In [17]:
print(df.loc[0:3])

   Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2         1       3                              Miss. Laina Heikkinen
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0    male  22.0                        1                        0   7.2500
1  female  38.0                        1                        0  71.2833
2  female  26.0                        0                        0   7.9250
3  female  35.0                        1                        0  53.1000

In [18]:
print(df.iloc[0:3])

   Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2         1       3                              Miss. Laina Heikkinen

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0    male  22.0                        1                        0   7.2500
1  female  38.0                        1                        0  71.2833
2  female  26.0                        0                        0   7.9250

In [21]:
print("Older passengers")
print(df[df['Age']>30].value_counts())
print("============================")
print(df[df['Age']>30].head())

Older passengers
Survived  Pclass  Name                                                Sex     Age   Siblings/Spouses Aboard  Parents/Children Aboard  Fare
1         1       Mrs. John Bradley (Florence Briggs Thayer) Cumings  female  38.0  1                        0                        71.2833    1
                  Mrs. Jacques Heath (Lily May Peel) Futrelle         female  35.0  1                        0                        53.1000    1
0         3       Mr. William Henry Allen                             male    35.0  0                        0                        8.0500     1
          1       Mr. Timothy J McCarthy                              male    54.0  0                        0                        51.8625    1
1         1       Miss. Elizabeth Bonnell                             female  58.0  0                        0                        26.5500    1
                                                                                                                                                ..
0         3       Mr. Victor Vander Cruyssen                          male    47.0  0                        0                        9.0000     1
1         1       Mrs. Thomas Jr (Lily Alexenia Wilson) Potter        female  56.0  0                        1                        83.1583    1
0         3       Mr. Johann Markun                                   male    33.0  0                        0                        7.8958     1
                  Mrs. William (Margaret Norton) Rice                 female  39.0  0                        5                        29.1250    1
                  Mr. Patrick Dooley                                  male    32.0  0                        0                        7.7500     1
Name: count, Length: 362, dtype: int64
============================
    Survived  Pclass                                               Name  \
1          1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
3          1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
4          0       3                            Mr. William Henry Allen
6          0       1                             Mr. Timothy J McCarthy
11         1       1                            Miss. Elizabeth Bonnell

       Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
1   female  38.0                        1                        0  71.2833
3   female  35.0                        1                        0  53.1000
4     male  35.0                        0                        0   8.0500
6     male  54.0                        0                        0  51.8625
11  female  58.0                        0                        0  26.5500

In [23]:
#Female old people
print((df['Age'] > 30) & (df['Sex'] == 'female').value_counts())

0      False
1       True
2      False
3      False
4      False
       ...
882    False
883    False
884    False
885    False
886    False
Length: 887, dtype: bool

In [25]:
print(df[df['Survived'] == 1])

     Survived  Pclass                                               Name  \
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2           1       3                              Miss. Laina Heikkinen
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
8           1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9           1       2                 Mrs. Nicholas (Adele Achem) Nasser
..        ...     ...                                                ...
871         1       3                           Miss. Adele Kiamie Najib
875         1       1       Mrs. Thomas Jr (Lily Alexenia Wilson) Potter
876         1       2        Mrs. William (Imanita Parrish Hall) Shelley
883         1       1                        Miss. Margaret Edith Graham
885         1       1                               Mr. Karl Howell Behr

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
1    female  38.0                        1                        0  71.2833
2    female  26.0                        0                        0   7.9250
3    female  35.0                        1                        0  53.1000
8    female  27.0                        0                        2  11.1333
9    female  14.0                        1                        0  30.0708
..      ...   ...                      ...                      ...      ...
871  female  15.0                        0                        0   7.2250
875  female  56.0                        0                        1  83.1583
876  female  25.0                        0                        1  26.0000
883  female  19.0                        0                        0  30.0000
885    male  26.0                        0                        0  30.0000

[342 rows x 8 columns]

In [26]:
survivors = df[df['Survived'] == 1]

In [28]:
print(survivors.loc[0:10,'Name'])

1     Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                 Miss. Laina Heikkinen
3           Mrs. Jacques Heath (Lily May Peel) Futrelle
8      Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9                    Mrs. Nicholas (Adele Achem) Nasser
10                       Miss. Marguerite Rut Sandstrom
Name: Name, dtype: str

In [29]:
#Select the first 10 rowws using iloc
print(df.iloc[0:11])

    Survived  Pclass                                               Name  \
0          0       3                             Mr. Owen Harris Braund
1          1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2          1       3                              Miss. Laina Heikkinen
3          1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
4          0       3                            Mr. William Henry Allen
5          0       3                                    Mr. James Moran
6          0       1                             Mr. Timothy J McCarthy
7          0       3                      Master. Gosta Leonard Palsson
8          1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9          1       2                 Mrs. Nicholas (Adele Achem) Nasser
10         1       3                     Miss. Marguerite Rut Sandstrom

       Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0     male  22.0                        1                        0   7.2500
1   female  38.0                        1                        0  71.2833
2   female  26.0                        0                        0   7.9250
3   female  35.0                        1                        0  53.1000
4     male  35.0                        0                        0   8.0500
5     male  27.0                        0                        0   8.4583
6     male  54.0                        0                        0  51.8625
7     male   2.0                        3                        1  21.0750
8   female  27.0                        0                        2  11.1333
9   female  14.0                        1                        0  30.0708
10  female   4.0                        1                        1  16.7000

In [30]:
#select rows 5-25 using iloc
print(df.iloc[5:16])

    Survived  Pclass                                              Name  \
5          0       3                                   Mr. James Moran
6          0       1                            Mr. Timothy J McCarthy
7          0       3                     Master. Gosta Leonard Palsson
8          1       3  Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9          1       2                Mrs. Nicholas (Adele Achem) Nasser
10         1       3                    Miss. Marguerite Rut Sandstrom
11         1       1                           Miss. Elizabeth Bonnell
12         0       3                     Mr. William Henry Saundercock
13         0       3                        Mr. Anders Johan Andersson
14         0       3               Miss. Hulda Amanda Adolfina Vestrom
15         1       2                    Mrs. (Mary D Kingcome) Hewlett

       Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
5     male  27.0                        0                        0   8.4583
6     male  54.0                        0                        0  51.8625
7     male   2.0                        3                        1  21.0750
8   female  27.0                        0                        2  11.1333
9   female  14.0                        1                        0  30.0708
10  female   4.0                        1                        1  16.7000
11  female  58.0                        0                        0  26.5500
12    male  20.0                        0                        0   8.0500
13    male  39.0                        1                        5  31.2750
14  female  14.0                        0                        0   7.8542
15  female  55.0                        0                        0  16.0000

In [31]:
#select rows with index labels 5-15 using loc
print(df.loc[5:15])

    Survived  Pclass                                              Name  \
5          0       3                                   Mr. James Moran
6          0       1                            Mr. Timothy J McCarthy
7          0       3                     Master. Gosta Leonard Palsson
8          1       3  Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9          1       2                Mrs. Nicholas (Adele Achem) Nasser
10         1       3                    Miss. Marguerite Rut Sandstrom
11         1       1                           Miss. Elizabeth Bonnell
12         0       3                     Mr. William Henry Saundercock
13         0       3                        Mr. Anders Johan Andersson
14         0       3               Miss. Hulda Amanda Adolfina Vestrom
15         1       2                    Mrs. (Mary D Kingcome) Hewlett

       Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
5     male  27.0                        0                        0   8.4583
6     male  54.0                        0                        0  51.8625
7     male   2.0                        3                        1  21.0750
8   female  27.0                        0                        2  11.1333
9   female  14.0                        1                        0  30.0708
10  female   4.0                        1                        1  16.7000
11  female  58.0                        0                        0  26.5500
12    male  20.0                        0                        0   8.0500
13    male  39.0                        1                        5  31.2750
14  female  14.0                        0                        0   7.8542
15  female  55.0                        0                        0  16.0000

In [33]:
#select the 'name' , 'age' , 'sex' columns for the forst 5 rows
print(df.loc[0:5 , ['Name','Age','Sex']])

                                                Name   Age     Sex
0                             Mr. Owen Harris Braund  22.0    male
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0  female
2                              Miss. Laina Heikkinen  26.0  female
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  35.0  female
4                            Mr. William Henry Allen  35.0    male
5                                    Mr. James Moran  27.0    male

In [34]:
#select the 'fare' column as a Series
print(df.loc[:,'Fare'])

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
882    13.0000
883    30.0000
884    23.4500
885    30.0000
886     7.7500
Name: Fare, Length: 887, dtype: float64

In [38]:
#find all male passengers

print(df[df['Sex'] == 'male'])

     Survived  Pclass                           Name   Sex   Age  \
0           0       3         Mr. Owen Harris Braund  male  22.0
4           0       3        Mr. William Henry Allen  male  35.0
5           0       3                Mr. James Moran  male  27.0
6           0       1         Mr. Timothy J McCarthy  male  54.0
7           0       3  Master. Gosta Leonard Palsson  male   2.0
..        ...     ...                            ...   ...   ...
879         0       2   Mr. Frederick James Banfield  male  28.0
880         0       3          Mr. Henry Jr Sutehall  male  25.0
882         0       2           Rev. Juozas Montvila  male  27.0
885         1       1           Mr. Karl Howell Behr  male  26.0
886         0       3             Mr. Patrick Dooley  male  32.0

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0                          1                        0   7.2500
4                          0                        0   8.0500
5                          0                        0   8.4583
6                          0                        0  51.8625
7                          3                        1  21.0750
..                       ...                      ...      ...
879                        0                        0  10.5000
880                        0                        0   7.0500
882                        0                        0  13.0000
885                        0                        0  30.0000
886                        0                        0   7.7500

[573 rows x 8 columns]

In [39]:
#find all passengers under 18
print(df[df['Age'] < 18])

     Survived  Pclass                                 Name     Sex   Age  \
7           0       3        Master. Gosta Leonard Palsson    male   2.0
9           1       2   Mrs. Nicholas (Adele Achem) Nasser  female  14.0
10          1       3       Miss. Marguerite Rut Sandstrom  female   4.0
14          0       3  Miss. Hulda Amanda Adolfina Vestrom  female  14.0
16          0       3                  Master. Eugene Rice    male   2.0
..        ...     ...                                  ...     ...   ...
849         1       1             Miss. Mary Conover Lines  female  16.0
859         0       3             Miss. Dorothy Edith Sage  female  14.0
865         1       3       Master. Harold Theodor Johnson    male   4.0
871         1       3             Miss. Adele Kiamie Najib  female  15.0
884         0       3       Miss. Catherine Helen Johnston  female   7.0

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare
7                          3                        1  21.0750
9                          1                        0  30.0708
10                         1                        1  16.7000
14                         0                        0   7.8542
16                         4                        1  29.1250
..                       ...                      ...      ...
849                        0                        1  39.4000
859                        8                        2  69.5500
865                        1                        1  11.1333
871                        0                        0   7.2250
884                        1                        2  23.4500

[130 rows x 8 columns]

In [43]:
#find all first class passengers who survived
pclass = df[df['Pclass'] == 1]
print(pclass['Survived'] == 1)

1       True
3       True
6      False
11      True
23      True
       ...
867     True
868    False
875     True
883     True
885     True
Name: Survived, Length: 216, dtype: bool

In [45]:
print(df[(df['Pclass'] == 1) & (df['Survived'] == 1)])

     Survived  Pclass                                               Name  \
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
11          1       1                            Miss. Elizabeth Bonnell
23          1       1                        Mr. William Thompson Sloper
31          1       1      Mrs. William Augustus (Marie Eugenie) Spencer
..        ...     ...                                                ...
858         1       1  Mrs. Frederick Joel (Margaret Welles Barron) S...
867         1       1    Mrs. Richard Leonard (Sallie Monypeny) Beckwith
875         1       1       Mrs. Thomas Jr (Lily Alexenia Wilson) Potter
883         1       1                        Miss. Margaret Edith Graham
885         1       1                               Mr. Karl Howell Behr

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard      Fare
1    female  38.0                        1                        0   71.2833
3    female  35.0                        1                        0   53.1000
11   female  58.0                        0                        0   26.5500
23     male  28.0                        0                        0   35.5000
31   female  48.0                        1                        0  146.5208
..      ...   ...                      ...                      ...       ...
858  female  48.0                        0                        0   25.9292
867  female  47.0                        1                        1   52.5542
875  female  56.0                        0                        1   83.1583
883  female  19.0                        0                        0   30.0000
885    male  26.0                        0                        0   30.0000

[136 rows x 8 columns]

In [46]:
#find female passengers who paid more than $100
df.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [47]:
print(df[(df['Sex'] == 'feamle') & (df['Fare'] > 100)])

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, Siblings/Spouses Aboard, Parents/Children Aboard, Fare]
Index: []

In [48]:
#find all passengers between the age of 20 and 30
print(df[(df['Age']>20) & (df['Age'] < 30)])

     Survived  Pclass                                              Name  \
0           0       3                            Mr. Owen Harris Braund
2           1       3                             Miss. Laina Heikkinen
5           0       3                                   Mr. James Moran
8           1       3  Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
17          1       2                       Mr. Charles Eugene Williams
..        ...     ...                                               ...
878         0       3                       Miss. Gerda Ulrika Dahlberg
879         0       2                      Mr. Frederick James Banfield
880         0       3                             Mr. Henry Jr Sutehall
882         0       2                              Rev. Juozas Montvila
885         1       1                              Mr. Karl Howell Behr

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0      male  22.0                        1                        0   7.2500
2    female  26.0                        0                        0   7.9250
5      male  27.0                        0                        0   8.4583
8    female  27.0                        0                        2  11.1333
17     male  23.0                        0                        0  13.0000
..      ...   ...                      ...                      ...      ...
878  female  22.0                        0                        0  10.5167
879    male  28.0                        0                        0  10.5000
880    male  25.0                        0                        0   7.0500
882    male  27.0                        0                        0  13.0000
885    male  26.0                        0                        0  30.0000

[270 rows x 8 columns]

In [50]:
#find male survivor under 25
survivor = df[df['Survived'] == 1]
print(survivor[(survivor['Sex'] == 'male') & survivor['Age']<25 ])

     Survived  Pclass                                               Name  \
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2           1       3                              Miss. Laina Heikkinen
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
8           1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9           1       2                 Mrs. Nicholas (Adele Achem) Nasser
..        ...     ...                                                ...
871         1       3                           Miss. Adele Kiamie Najib
875         1       1       Mrs. Thomas Jr (Lily Alexenia Wilson) Potter
876         1       2        Mrs. William (Imanita Parrish Hall) Shelley
883         1       1                        Miss. Margaret Edith Graham
885         1       1                               Mr. Karl Howell Behr

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
1    female  38.0                        1                        0  71.2833
2    female  26.0                        0                        0   7.9250
3    female  35.0                        1                        0  53.1000
8    female  27.0                        0                        2  11.1333
9    female  14.0                        1                        0  30.0708
..      ...   ...                      ...                      ...      ...
871  female  15.0                        0                        0   7.2250
875  female  56.0                        0                        1  83.1583
876  female  25.0                        0                        1  26.0000
883  female  19.0                        0                        0  30.0000
885    male  26.0                        0                        0  30.0000

[342 rows x 8 columns]

In [51]:
#find female non-survivors over 50
print(df[(df['Sex'] == 'female') & (df['Survived'] == 0) & (df['Age'] > 50)])

     Survived  Pclass                           Name     Sex   Age  \
561         0       3  Miss. (Marion Ogden) Meanwell  female  62.0
768         0       2               Mrs. (Mary) Mack  female  57.0

     Siblings/Spouses Aboard  Parents/Children Aboard   Fare
561                        0                        0   8.05
768                        0                        0  10.50

In [52]:
#find first-class passengers who dies but paid over $100
print(df[(df['Pclass'] == 1) & (df['Survived'] ==0) & (df['Fare'] > 100)])

     Survived  Pclass                                            Name     Sex  \
27          0       1                   Mr. Charles Alexander Fortune    male
117         0       1                         Mr. Quigg Edmond Baxter    male
295         0       1                     Miss. Helen Loraine Allison  female
330         0       1                        Mr. George Edward Graham    male
371         0       1                              Mr. Sante Ringhini    male
375         0       1                        Mr. Harry Elkins Widener    male
435         0       1                                Mr. Mark Fortune    male
495         0       1  Mrs. Hudson J C (Bessie Waldo Daniels) Allison  female
502         0       1       Mr. Victor de Satode Penasco y Castellana    male
524         0       1                               Mr. John Farthing    male
541         0       1                       Mr. Walter Donald Douglas    male
554         0       1                              Mr. Victor Robbins    male
656         0       1                       Mr. Arthur Webster Newell    male
695         0       1                         Mr. John Borland Thayer    male

      Age  Siblings/Spouses Aboard  Parents/Children Aboard      Fare
27   19.0                        3                        2  263.0000
117  24.0                        0                        1  247.5208
295   2.0                        1                        2  151.5500
330  38.0                        0                        1  153.4625
371  22.0                        0                        0  135.6333
375  27.0                        0                        2  211.5000
435  64.0                        1                        4  263.0000
495  25.0                        1                        2  151.5500
502  18.0                        1                        0  108.9000
524  49.0                        0                        0  221.7792
541  50.0                        1                        0  106.4250
554  45.0                        0                        0  227.5250
656  58.0                        0                        2  113.2750
695  49.0                        1                        1  110.8833

In [53]:
#find passengers who were alone
df.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [54]:
print(df.columns)

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Siblings/Spouses Aboard',
       'Parents/Children Aboard', 'Fare'],
      dtype='str')

In [55]:
print(df[(df['Parents/Children Aboard'] == 0 ) & (df['Siblings/Spouses Aboard'] == 0)])

     Survived  Pclass                         Name     Sex   Age  \
2           1       3        Miss. Laina Heikkinen  female  26.0
4           0       3      Mr. William Henry Allen    male  35.0
5           0       3              Mr. James Moran    male  27.0
6           0       1       Mr. Timothy J McCarthy    male  54.0
11          1       1      Miss. Elizabeth Bonnell  female  58.0
..        ...     ...                          ...     ...   ...
880         0       3        Mr. Henry Jr Sutehall    male  25.0
882         0       2         Rev. Juozas Montvila    male  27.0
883         1       1  Miss. Margaret Edith Graham  female  19.0
885         1       1         Mr. Karl Howell Behr    male  26.0
886         0       3           Mr. Patrick Dooley    male  32.0

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare
2                          0                        0   7.9250
4                          0                        0   8.0500
5                          0                        0   8.4583
6                          0                        0  51.8625
11                         0                        0  26.5500
..                       ...                      ...      ...
880                        0                        0   7.0500
882                        0                        0  13.0000
883                        0                        0  30.0000
885                        0                        0  30.0000
886                        0                        0   7.7500

[533 rows x 8 columns]

In [58]:
#find the oldest female survivor
female_survivor = df[(df['Sex'] == 'female') & (df['Survived'] == 1)]
max_age = female_survivor['Age'].max()
oldest_female_survivor = female_survivor[female_survivor['Age'] == max_age]
print(oldest_female_survivor)

     Survived  Pclass                              Name     Sex   Age  \
273         1       1  Miss. Kornelia Theodosia Andrews  female  63.0
480         1       3             Mrs. (Hedwig) Turkula  female  63.0

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare
273                        1                        0  77.9583
480                        0                        0   9.5875

In [60]:
#youngest male who died
male_diers = df[(df['Sex'] == 'male') & (df['Survived'] == 0)]
min_age = male_diers['Age'].min()
print(male_diers[male_diers['Age'] == min_age])

     Survived  Pclass                            Name   Sex  Age  \
163         0       3     Master. Eino Viljami Panula  male  1.0
384         0       3  Master. Sidney Leonard Goodwin  male  1.0

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare
163                        4                        1  39.6875
384                        5                        2  46.9000